;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0
	.word @sfx_ntsc_1
	.word @sfx_ntsc_2
@pal:
	.word @sfx_pal_0
	.word @sfx_pal_1
	.word @sfx_pal_2

@sfx_ntsc_0:
	.byte $83,$b8,$84,$e1,$85,$00,$02,$84,$d5,$02,$84,$bd,$01,$84,$a9,$07
	.byte $00
@sfx_pal_0:
	.byte $83,$b8,$84,$d1,$85,$00,$02,$84,$c6,$02,$84,$b0,$01,$84,$9d,$05
	.byte $00
@sfx_ntsc_1:
	.byte $83,$ba,$84,$0c,$85,$01,$02,$84,$fd,$85,$00,$02,$84,$e1,$01,$84
	.byte $c9,$07,$00
@sfx_pal_1:
	.byte $83,$ba,$84,$f9,$85,$00,$02,$84,$eb,$02,$84,$d1,$01,$84,$ba,$05
	.byte $00
@sfx_ntsc_2:
	.byte $89,$3c,$8a,$02,$02,$8a,$01,$02,$8a,$0f,$01,$8a,$0d,$07,$00
@sfx_pal_2:
	.byte $89,$3c,$8a,$02,$02,$8a,$01,$02,$8a,$0f,$01,$8a,$0d,$05,$00
